fix: use correct url parameter for merchant hash generation
paytrail/examples pull request #5
Opened 2020-07-02 05:08 UTC by Jipsukka

## What type of Pull Request is this?

Check all the applicable.

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Merchant API hash generation had wrong URL. Paytrail API URL is not part of URL used in hash calculation.

## Tests

- [ ] Not needed
- [ ] Unit tests added
- [ ] Integration tests added
- [x] Visual verification done

## Related Tickets & Documents

Link to any known issues by prefixing the issue number with `#` (e.g. `Related to #1`).

## Code of Conduct

- [x] I have read and agreed to the [community code of conduct][coc]. The sole intention of this pull request is to improve the project codebase.

[coc]: https://github.com/paytrail/.github/blob/master/CODE_OF_CONDUCT.md

2020-07-02 05:11 UTC, laurasaari approved these changes

2020-07-02 05:48 UTC, nikoheikkila requested changes

2020-07-02 05:48 UTC, nikoheikkila commented on PHP/CalculateMerchantApiHash.php
> +/payments/102402728626/refunds
Should this be in the format `/merchant/v1/payments/:id/refunds` like described in the [documentation](https://docs.paytrail.com/merchant-api/v1/accessing/)?

2020-07-02 13:15 UTC, Jipsukka commented on PHP/CalculateMerchantApiHash.php
> +/payments/102402728626/refunds
No, since this is exact output what `$hashHmacContent` value is.

2020-07-03 06:17 UTC, nikoheikkila approved these changes

2020-07-03 06:17 UTC, merged